version: '3.9'

services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: always
    hostname: "${HOSTNAME}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://${HOSTNAME}"
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        letsencrypt['enable'] = false
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/${HOSTNAME}.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/${HOSTNAME}.key"
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
      - ./ssl:/etc/gitlab/ssl
    shm_size: '256m'
    networks:
      - gitlab_net

networks:
  gitlab_net:
    driver: bridge
